name: Release
on:
  pull_request:
    types: [closed]
    branches:
      - release

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    name: Publish GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
      - name: Publish GitHub Release
        run: |
          git remote set-url origin "https://$GITHUB_ACTOR:$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git checkout master
          npm i global standard-version
          standard-version
          git push --follow-tags origin master
        env:
          CI: 'true'
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
