name: Test
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install yarn
        run: npm install yarn -g
      - name: Install Dependencies
        run: yarn --force
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
        env:
          CI: true
          NODE_ENV: production
